/***************************************
				GROUP-08
  Yash Bansal			-   2019A7PS0484P
  Sourabh S Yelluru		-   2018B3A70815P
  Nihir Agarwal			-   2018B4A70701P
  Aakash				-   2018B4A70887P
*****************************************/
// TODO change all temp and bruh
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <time.h>

#include "lexer.h"
#include "parser.h"
#include "ast.h"
#include "symbolTable.h"
#include "typeChecker.h"
#include "logger.h"

#define MAX_OPTIONS 11

void clear_screen()
{
#ifdef _WIN32
	system("cls");
#endif
#ifdef _WIN64
	system("cls");
#endif
#ifdef __unix__
	system("clear");
#endif
#ifdef __linux__
	system("clear");
#endif
}

void main(int argc, char **argv)
{
	clear_screen();
	loadLexer();
	loadParser();

	if (argc != 2)
	{
		fprintf(stderr, "usage: stage1exe <source_code_file>\n");
		exit(-1);
	}

	freopen("compiler.log", "w", stderr);

	int option = 0;
	int start = 1;
	char c;

	clock_t start_time = clock();
	clock_t end_time = start_time;

	do
	{
		if (!start)
		{
			printf("Press any key to continue...");
			scanf("%c", &c);
			clear_screen();
		}
		start = 0;

		printf("Following are the options to select from\n");
		printf("0: Exit\n");
		printf("1: Print token list generated by lexer\n");
		printf("2: Parse the source code and print Parse Tree to console\n");
		printf("3: Print Abstract Syntax Tree to console using DFS\n");
		printf("4: Display Compression\n");
		printf("5: Print Symbol Table\n");
		printf("6: Global Variables\n");
		printf("7. \n");
		printf("11: Compile\n");

		printf("Select an option: ");
		scanf("%d", &option);
		while ((c = getchar()) != '\n' && c != EOF)
			;
		clear_screen();

		if (option < 0 || option > MAX_OPTIONS)
		{
		}

		if (option == 0)
		{
			freeLexerData();
			printf("Bye bye from group 8 compiler\n");
			break;
		}
		/*if (option == 4)
		{
			start_time = clock();
			TreeNode *node = parseInputSourceCode(argv[1]);
			end_time = clock();
			double total_CPU_time = (double)(end_time - start_time);
			printf("Total CPU Time Taken: %f\n", total_CPU_time);
			printf("Total CPU Time taken in seconds: %f\n", total_CPU_time / CLOCKS_PER_SEC);
			freeParseTree(node);
			continue;
		}
		*/
		else if (option == 1)
			printLexerOutput(argv[1]);
		else if (option == 2)
		{
			TreeNode *node = parseInputSourceCode(argv[1]);

			// FILE* fptr = fopen(argv[2], "w");
			printf("Group 8 Output File.\n%25s %14s %11s %18s %24s %12s %29s\n",
				   "Lexeme",
				   "LineNumber",
				   "TokenName",
				   "Value (if Num)",
				   "ParentSymbol",
				   "Is Leaf",
				   "NodeSymbol");

			printParseTree(node);

			freeParseTree(node);
		}
		else if (option == 3)
		{
			TreeNode *node = parseInputSourceCode(argv[1]);
			ASTNode *ast = createAST(node);
			printAST(ast, 0);
		}
		else if (option == 4)
		{
			TreeNode *node = parseInputSourceCode(argv[1]);
			ASTNode *ast = createAST(node);

			int numParseTreeNodes = 0;
			int parseTreeSize = 0;
			int numASTNodes = 0;
			int ASTSize = 0;

			ParseTreeDfs(node, &numParseTreeNodes, &parseTreeSize);
			ASTDfs(ast, &numASTNodes, &ASTSize);

			printf("Parse tree Number of nodes = %d Allocated Memory = %d Bytes\n", numParseTreeNodes, parseTreeSize);
			printf("AST Number of nodes = %d Allocated Memory = %d Bytes\n", numASTNodes, ASTSize);
			float Compression = (float)(parseTreeSize - ASTSize) / parseTreeSize * 100;
			printf("Compression percentage = ((%d - %d) / %d) * 100 = %.2f%c\n", parseTreeSize, ASTSize, parseTreeSize, Compression, '%');
		}
		else if (option == 5)
		{
			TreeNode *node = parseInputSourceCode(argv[1]);
			ASTNode *ast = createAST(node);
			loadSymbolTable(ast);
			// iterateTrie(globalSymbolTable, printGlobalSymbolTable);
		}
		else if (option == 11)
		{
			TreeNode *node = parseInputSourceCode(argv[1]);
			// printParseTree(node);

			ASTNode *ast = createAST(node);

			loadSymbolTable(ast);

			typeChecker_init();
			assignTypes(ast);
		}
		else
		{
			printf("Invalid option selected: %d\n", option);
			continue;
		}

	} while (option != 0);
}
